version: "3.3"

services:
  app:
    build:
      context: .
      args:
        - ARCH
        - SNAPCAST_VERSION
    image: mazzolino/snapcast-client:${SNAPCAST_VERSION}-${ARCH}
    devices:
      - /dev/snd
